"""Pure code generation for the experimental spell-card editor."""

from __future__ import annotations

import re
from typing import Any


def _class_name(name: str) -> str:
    words = re.split(r"[\s「」]+", name)
    value = "".join(word.title() for word in words)
    value = "".join(char for char in value if char.isalnum() or char == "_")
    if not value:
        return "CustomSpellCard"
    if value[0].isdigit():
        value = f"Spell{value}"
    return value


def build_spellcard_code(spellcard: Any) -> str:
    """Build source compatible with the current async ``SpellCard`` API."""
    name = str(spellcard.name)
    class_name = _class_name(name)
    bonus = int(getattr(spellcard, "bonus", 1_000_000))

    lines = [
        '"""',
        name,
        "",
        "Generated by the experimental PySTG spell-card editor.",
        '"""',
        "",
        "from src.game.stage.spellcard import SpellCard",
        "import math",
        "import random",
        "",
        "",
        f"class {class_name}(SpellCard):",
        f"    name = {name!r}",
        f"    hp = {int(spellcard.hp)}",
        f"    time_limit = {int(spellcard.time_limit)}",
        f"    bonus = {bonus}",
        "",
        "    async def setup(self):",
        (
            "        await self.boss.move_to("
            f"{float(spellcard.boss_x)!r}, {float(spellcard.boss_y)!r}, duration=60)"
        ),
        "",
        "    async def run(self):",
        "        angle_offset = 0",
        "",
        "        while True:",
    ]

    patterns = getattr(spellcard, "patterns", {})
    for pattern in patterns.values():
        lines.append(f"            # === {pattern.name} ===")
        pattern_type = str(pattern.pattern_type)
        count = int(pattern.count)
        interval = int(pattern.interval)
        bullet_type = str(pattern.bullet_type)
        color = str(pattern.color)

        if pattern_type == "circle":
            lines.extend([
                "            self.fire_circle(",
                f"                count={count},",
                f"                speed={float(pattern.speed)!r},",
                "                start_angle=angle_offset,",
                f"                bullet_type={bullet_type!r},",
                f"                color={color!r},",
                "            )",
                "            angle_offset += 10",
            ])
        elif pattern_type == "aimed":
            lines.extend([
                f"            for i in range({count}):",
                "                self.fire_at_player(",
                f"                    speed={float(pattern.speed)!r} + i * 0.2,",
                f"                    bullet_type={bullet_type!r},",
                f"                    color={color!r},",
                "                )",
                f"                await self.wait({interval})",
            ])
        elif pattern_type == "spiral":
            lines.extend([
                f"            for i in range({count}):",
                "                self.fire(",
                (
                    "                    angle=angle_offset + i * "
                    f"({float(pattern.angle_spread)!r} / {max(1, count)}),"
                ),
                f"                    speed={float(pattern.speed)!r},",
                f"                    bullet_type={bullet_type!r},",
                f"                    color={color!r},",
                "                )",
            ])
            if interval > 0:
                lines.append(f"                await self.wait({interval})")
        elif pattern_type == "random":
            lines.extend([
                f"            for _ in range({count}):",
                "                angle = random.uniform(0, 360)",
                (
                    f"                speed = {float(pattern.speed)!r} + "
                    f"random.uniform(-{float(pattern.speed_var)!r}, "
                    f"{float(pattern.speed_var)!r})"
                ),
                "                self.fire(",
                "                    angle=angle,",
                "                    speed=speed,",
                f"                    bullet_type={bullet_type!r},",
                f"                    color={color!r},",
                "                )",
            ])
        else:
            lines.extend([
                f"            for i in range({count}):",
                "                self.fire(",
                f"                    angle={float(pattern.angle)!r},",
                (
                    f"                    speed={float(pattern.speed)!r} + "
                    f"i * {float(pattern.speed_var)!r},"
                ),
                f"                    bullet_type={bullet_type!r},",
                f"                    color={color!r},",
                "                )",
            ])

        lines.extend([
            "",
            f"            await self.wait({max(30, interval * count)})",
            "",
        ])

    if not patterns:
        lines.append("            await self.wait(60)")

    lines.extend(["", "", f"spellcard = {class_name}", ""])
    return "\n".join(lines)
